### ISSUE TITLE
window.cep is always undefined in react template

### ISSUE THREAD

**Issue by moorphism** [hyperbrew/bolt-cep#101]
Hey, Thanks for your great project. 

When i try to use evalTS or evalES i get an error: 

csinterface.js:608 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'evalScript') at CSInterface.evalScript.

So the interface wasn't loaded right. 

When i try to log window.cep it's always log undefined. 

How to fix it ?

Thanks in advance!

**Comment by justintaylor-dev** [comment]
Sounds like you're testing in the browser if `window.cep` isn't defined. Try testing in your host app instead. If you have more questions on getting started with Bolt CEP, join our Discord:

https://discord.gg/PC3EvvuRbc
