### ISSUE TITLE
Audition support

### ISSUE THREAD

**Issue by havremunken** [hyperbrew/bolt-cep#102]
Is it possible to ask if support for Adobe Audition would be possible with Bolt? I realize I am probably the one person in the universe wanting it, so I would be willing to put in some work, but I am completely unfamiliar with Bolt and don't know what kind of tasks this would include. Could I please ask for some pointers?

**Comment by justintaylor-dev** [comment]
Hey, so yes this would be a good addition to the CLI setup, but for now you can use Audition following these steps:

- Create a new Bolt CEP project from the Demo
- Add the right host to `cep.config.ts` ( `AUDT` for Audition in this case )
- Duplicate one of the app folders in jsx (like `ppro` for example) and rename the folder to `audt` and main file to `audt.ts`
- Update the types-for-adobe typse path in `jsx/audt/tsconfig.json` removing the Premiere types and adding the path to the Audition types in the types-for-adobe folder (`"../../../node_modules/types-for-adobe/Audition/2018"`)
- Create a new switch option for Audition in `index.ts` 
```js
import * as audt from "./audt/audt";
[...]
  case "audition":
  case "auditionbeta":
    main = audt;
    break;
[...]
typeof audt &
[...]
```
- Run `yarn build` and restart Audition, your extension should be picked up.

**Comment by havremunken** [comment]
Thanks, Justin, I will try this for now, and get to know Bolt a bit better (not to mention the Audition API). If I manage to wrap my head around things, I might try to contribute to the project once I get to a happy place. :)

Thanks again!

**Comment by justintaylor-dev** [comment]
Sure thing, best of luck! 👍🏻

**Comment by justintaylor-dev** [comment]
Bolt CEP now supports Audition in 1.2.0

**Comment by havremunken** [comment]
Wow, that is awesome! I got stuck on another project before I could test your instructions, but I am getting to this shortly, and will take it for a spin!
