### ISSUE TITLE
zxp password included as raw text in build bundle

### ISSUE THREAD

**Issue by lucadalli** [hyperbrew/bolt-cep#112]
I am new to CEP plugin development and unfamiliar with the whole signing process but I noticed that the `zxp.password` is included as raw text in the `jsx/index.js` file of the build bundle.

Is this a security concern?

**Comment by justintaylor-dev** [comment]
Not if you're self-signing, if you want to sign with real paid certs then yea that could be a concern, but ZXP security isn't correctly implemented so there's really no point. To avoid this from showing up in the bundle then just don't import the config to get the id, just copy it manually or stick it in another file that you import.

If you want to chat more general topics like this for Bolt CEP, feel free to join our Discord:  https://discord.gg/PC3EvvuRbc

**Comment by lucadalli** [comment]
Hi Justin,

Thanks for clarifying! I have joined the Discord.

Kind regards,
Luca
