### ISSUE TITLE
API requests 

### ISSUE THREAD

**Issue by Dando54** [hyperbrew/bolt-cep#113]
Hi, I just found out this amazing boilerplate, I know it is possible to get a video's metadata via ExtendScript but is it possible to make an HTTP/HTTPs request to my API in order to send that metadata or can it be done only via websockets ?

**Comment by justintaylor-dev** [comment]
From the CEP side you can use `fetch()` or if you hit CORS issues that you can't fix, you can use native Node.js `http` or `https` modules. For more general discussions like this feel free to join our Discord: https://discord.gg/PC3EvvuRbc
