### ISSUE TITLE
"TypeError: undefined is not an object" when calling evalEs

### ISSUE THREAD

**Issue by gorlikariel** [hyperbrew/bolt-cep#118]
mac m1
This error suddenly started showing up out of nowhere...
Even after rolling back to commits that did work, it doesn't help.

**Comment by gorlikariel** [comment]
Reverting back to an old commit where everything worked didn't help (even after re-building), something broke in the interaction between bolt and csi

**Comment by justintaylor-dev** [comment]
Ensure your Apple Silicon machine is setup correctly:

https://hyperbrew.co/blog/setup-extendscript-dev-for-apple-silicon/

If you're still having issues on a fresh Bolt CEP project, (i.e. even the example functions don't work) please provide your system specs and app details.

**Comment by justintaylor-dev** [comment]
Assuming this issue is resolved, if it comes up again, feel free to re-open
