### ISSUE TITLE
[Question] Using HMR within Adobe apps?

### ISSUE THREAD

**Issue by KyleTryon** [hyperbrew/bolt-cep#119]
Hey all, first of all, thank you so much for making this.

I am attempting to write an extension (cep panel) for AE and just wondering how you all are testing the JSX.

I can run `yarn dev` to run the local server and access the frontend in the browser but I'm not clear on the best way to test within AE.

Right now what I am doing is running `yarn build` and manually moving the const of `dist` into the Adobe `cep` directory. But I think if I understand from the ReadMe, I am likely not doing that correctly.

Can HMR work directly within AE? Do I just want to setup a symlink or similar to map the dist?

Another fun quirk is I am on a Mac M1 right now which it seems has limited supported (or none) for the debuggers potentially but I will cross that bridge next.

**Comment by justintaylor-dev** [comment]
Hi Kyle!

Bolt CEP sets up the symlink for you after running `yarn build`, then run `yarn dev` to enable HMR after.

Also, we recently did a post on getting your M1/M2/M3 machine setup for Adobe ExtendScript dev:

https://hyperbrew.co/blog/setup-extendscript-dev-for-apple-silicon/

For general questions regarding how to use Bolt CEP, join our Discord:

https://discord.gg/PC3EvvuRbc

Thanks!
