### ISSUE TITLE
jsx strings are garbled（jsx字符串乱码问题）

### ISSUE THREAD

**Issue by divib-cc** [hyperbrew/bolt-cep#122]
When writing JSX, 
Chinese strings inside double quotes ("") may appear as garbled text, for example, alert("哈哈") displays as alert("鍝堝搱"). 
However, using template strings with backticks (``) will display correctly, for example, alert(`哈哈`) remains as alert(`哈哈`).

**Comment by aztack** [comment]
Check the file encoding If you are using Windows and ensure it is set to utf-8.

**Comment by divib-cc** [comment]
Solved
cep.config.ts
  build: {
    jsxBin: 'replace',
    sourceMap: false,
  },
