### ISSUE TITLE
copyAssets when `npm run dev` not only when building

### ISSUE THREAD

**Issue by aztack** [hyperbrew/bolt-cep#124]
Currently `copyAssets` only respected when building. But in some scenario assets copying need to be done when `npm run dev` started. Off course this can be done manually or with a custom vite plugin. But it would be great if it can be supported by bolt-cep through `copyAssets`.

**Comment by justintaylor-dev** [comment]
This is by design, any sort of copying of assets or modules only happens at build time. Dev is only for once you've run yarn build and you want to enable HMR.
