### ISSUE TITLE
Typo in vite --mode developemnt

### ISSUE THREAD

**Issue by iconictb** [hyperbrew/bolt-cep#18]
typo in package.json, line 5
vite --mode **developemnt**

Edit: actually not sure if this is coming from Bolt or [Vite addon](https://github.com/hyperbrew/vite-cep-plugin)

**Comment by justintaylor-dev** [comment]
Thanks for catching that, turns out the flag is no longer required in Vite anyway.

Fixed in 3be26f8f42adc99c774cf1eac5283c871d9ca4bf
