### ISSUE TITLE
yarn build: ERR_FILE_NOT_FOUND due to loading from filesystem root

### ISSUE THREAD

**Issue by borisboguslavsky** [hyperbrew/bolt-cep#19]
After running `yarn build`, the extension builds fine and seems to place everything where it should but for all my fonts and SVG files that have to be loaded in via CSS, I get the following error in the browser console:

`index.html:52 GET file:///C:/assets/WebFontOrSVG.ext net::ERR_FILE_NOT_FOUND`

This occurs for all assets that are linked inside of CSS files. The filepath for these assets becomes prefixed with the root of the filesystem, so the C:/ drive for Windows machines and / for MacOS.

This doesn't occur if I run `yarn dev` and load the extension in the development mode.

The reason for this is that in the final compiled CSS file inside of dist/js, all paths to external files are prefixed with `'/assets/'` when they should be prefixed with `'./'`

Running a search and replace to replace all occurrences of '/assets/' with './' inside of the final merged and minified CSS file acts as a workaround for this issue.

**Comment by justintaylor-dev** [comment]
Thanks for finding this. Resolved in https://github.com/hyperbrew/vite-cep-plugin/commit/862a166e392c0a9ead1e3bc65e1d0f61126bebfa
