### ISSUE TITLE
Error when bundling with zxp

### ISSUE THREAD

**Issue by gribias** [hyperbrew/bolt-cep#21]
hello! 
When I was running the command `yarn zxp` I was receiving an error about certificate file is not valid. 
Then I discovered that this issue is caused by the root name path of the project , for instance if you clone the repo in a folder named : "c:/users/documents/**Post production**/bolt-cep" 

![image](https://user-images.githubusercontent.com/23198548/166948611-b0ca0a8a-e54b-4cbb-be25-f88407ca2c42.png)

Then I renamed the folder name without any space between `Post-production` and everything is running fine.

**Comment by justintaylor-dev** [comment]
@gribias thanks for finding this! Corrected in `vite-cep-plugin` 0.1.7 https://github.com/hyperbrew/vite-cep-plugin/commit/b938962aa81484b2d7bfdce6ff94ef6628160f2d
