### ISSUE TITLE
Photoshop Persistent 

### ISSUE THREAD

**Issue by gribias** [hyperbrew/bolt-cep#24]
Hi! 
Is it possible to set the CEP panel persistent? 

```
 var csInterface = new CSInterface();
 event = new CSEvent("com.adobe.PhotoshopPersistent", "APPLICATION");
 event.extensionId = csInterface.getExtensionID();
 csInterface.dispatchEvent(event);
```
I did with `csi` from utils.ts but it didn't work.
thanks!

**Comment by justintaylor-dev** [comment]
Hi @gribias ! Can you provide an example of how you're attempting this in Bolt with `csi`? CSEvent isn't currently being exported which might be part of the issue. 

I've updated `csinterface.js` to export all functions, so you can try importing it with

```
import CSInterface, {CSEvent, CSXSWindowType} from "../lib/csinterface";
```
etc.

If you update just `csinterface.js` or that file or create a new Bolt instance with `0.1.6`.

**Comment by gribias** [comment]
Hi @justintaylor-dev!
It's working now :)  I imported CSEvent like you just said.
One more thing, with your change I had to remove the  `OnAppThemeColorChanged ` because it's unavailable and I couldn't build with success .
Thank you for your fast reply!
