### ISSUE TITLE
dammit

### ISSUE THREAD

**Issue by yahiaboudah** [hyperbrew/bolt-cep#29]
I tried everything, I put it in installModules in the config, I tried require, I tried import, I tried using plugins, I tried using everything, it's just not working, please help I'm on a deadline

**Comment by yahiaboudah** [comment]
I even put it in the html, how do I integrate this child process thing?

**Comment by justintaylor-dev** [comment]
For anyone else who finds this thread, `child_process` is a built-in node module so it doesn't require bundling.

In Bolt, you can import with `import { child_process } from "../lib/node";`

**Comment by yahiaboudah** [comment]
Wait, I tried doing that and it's giving me this error:
```
src/js/lib/node.ts:15:20 - error TS2307: Cannot find module 'child_process' or its corresponding type declarations.

15 ) as typeof import("child_process");
```

**Comment by yahiaboudah** [comment]
For the now the error went away, and I am getting a proper build by adding nodeTypes to vite config in (resolve/alias):
```{ find: '@nodeTypes', replacement: path.resolve(__dirname, 'node_modules/@types/node') }```
and replacing child_process with ```"@nodeTypes/child_process"```.

However I will have to use some kind of placeholder to run in the web since the node stuff only runs within Adobe.

Anyway, thanks for the help

**Comment by justintaylor-dev** [comment]
Are you running Node.js 16 or up? The `/lib/node.ts` file already does that by returning a blank object if you're in the browser or the node module if you're in a node environment.

**Comment by yahiaboudah** [comment]
Node version: v16.13.1
