### ISSUE TITLE
Array destructuring transpiles into incompatible code

### ISSUE THREAD

**Issue by timhaywood** [hyperbrew/bolt-cep#30]
Unfortunetly, babel (purposefully) transpiles array destructuring into code that uses `Array.isArray`, even if that's not available in the target environment.

More info in this issue on the babel repo:
https://github.com/babel/babel/issues/11195

Don't expect a fix or anything, just wanted to call it out in case you hadn't run across it and wanted to call it out as a known limiation in the README or something.

I've just replaced the destructuring in my scripts manually.

Appreciate your hard work! Feel free to close without comment :)

**Comment by mgomez-tubs** [comment]
I ran across this today lol. Should probably be mentioned in the README. Luckily I dind't spent too much time debugging it (which is kinda hard, since it appears almost from nowhere). However, I found out that having certain panels open (?) allows you to use the Array.isArray function.

**Comment by timhaywood** [comment]
Yeah good idea, let me add a PR for updating the readme 👍

As for having panels open, scripts have access to the global object, so some may modify the global Array prototype to add `isArray`, which is why your script has access to it when they're open.

**Comment by justintaylor-dev** [comment]
@timhaywood @mgomez-tubs thanks for brining this up!

Built-in and custom Ponyfills have been implemented in 0.4.0 (see the Readme for details). 

I've added a Ponyfill for `Array.isArray` so array destructuring now works in ExtendScript.

Let me know if you run into any other issues. 🍻

**Comment by justintaylor-dev** [comment]
resolved in d3ca479054e9014a468caa50a41ab6cb46d66e9c

**Comment by timhaywood** [comment]
Amazing, thanks Justin!
