### ISSUE TITLE
Require pollyfill is (sometimes) called with incorrect `dirname`

### ISSUE THREAD

**Issue by timhaywood** [hyperbrew/bolt-cep#33]
I'm getting some errors when running monaco built with bolt-cep, which I believe is related to the file paths not being correctly fixed with the `/assets` prefix.

The issues seems to be caused by the `require` pollyfill being bound with the incorrect `basedir` in some cases. Not sure if this is something that falls within `vite-cep-plugin` to fix, or if it will come up in other repos.

## Current issue

[Repo link](https://github.com/motiondeveloper/editor)

When serving the built files, requests are being made to js assets that don't exist:

![image](https://user-images.githubusercontent.com/48076776/175879255-85b27f9d-89a5-4fdc-9514-9dfef64bcba3.png)

These files exist, but as expected are located in `/assets`. Following the stack track shows that the error is thrown in the `getSynchXHR()` function as a part of the `require()` polyfill inlined to `index.html`.

![image](https://user-images.githubusercontent.com/48076776/175879856-77fcffeb-f4f9-497a-b8de-62b951155414.png)

Following the function calls upwards, we can see that require is being called bound the to the root `dirname`, but without the `assets/` prefix.

![image](https://user-images.githubusercontent.com/48076776/175885613-55a46b2e-edd4-4da3-a888-d776b4ef0618.png)

This call can be seen in the source files, where `require()` is called:
```js
require("./typescript.80793909.js");
```

Originally I thought this was an issue that could be fixed at the `require()` call site, but then I realized there are other times when `require()` is bound to the correct `/assets` dirname:

![image](https://user-images.githubusercontent.com/48076776/175885655-9e318e88-a757-4dcf-88b5-e68b62b3c78f.png)

And adding `/assets` to the `require` call means that these executions result in the incorrect path `"assets/assets/...".

## Cause

The `dirname` arg is bound here:

![image](https://user-images.githubusercontent.com/48076776/175887684-d5e4725e-698d-4859-afb0-d98209fe283c.png)

Logging `dirname` show's how sometimes it contains `/assets` while other times it doesn't.
![image](https://user-images.githubusercontent.com/48076776/175894981-75a221f7-3534-446c-84b7-d6a94f772f5e.png)

`dirname` is bound to the result of `loadPrerequisites()`.  Still investigating why this is different across calls, considering `baseDir` only seems to be set once — to the base URL without `/assets`.

## Temporary fix

I was able to work around the issue by adding the following if statement to the require implementation to make sure asset paths are prefixed with `/assets`.

```js
function require(dirname, file) {
  file = typeof file === "string" ? file.trim() : "";
  if (!dirname.includes("/assets/")) {
    dirname = dirname + "assets/";
  }
  // ....
 ```

Which fixes the issue, but obviously isn't much of a solution! Let me know if you've run across anything similar, or if I've missed anything. Will continue investigating and see if I can work up a good fix.

**Comment by justintaylor-dev** [comment]
@timhaywood I've fixed a bunch of bugs with the asset paths since this comment. Let me know if this issue is still present. Thanks!

**Comment by justintaylor-dev** [comment]
Closing for now, feel free to reopen if this comes up again.

**Comment by timhaywood** [comment]
Yeah still having the same issue on the latest version unfortunately. Thanks for all the updates though!

I'll leave it closed for now, since I'm pretty sure it's isolated to the specific setup.

Will update here if I'm able to find a solution in case anyone else runs into the same issue.
