### ISSUE TITLE
using cep.util.registerExtensionUnloadCallback to save extension cache data

### ISSUE THREAD

**Issue by yahiaboudah** [hyperbrew/bolt-cep#34]
I'm trying to save cache data for the extension when it's closed. I've put this snippet in **index.tsx**, but it doesn't seem to be working.
Usually, I guess you'd put it inside the html file surrounded with a script tag or something. But in the context of React and Vite, I just don't know how I'd add the *onClose* callback

```js
cep.util.registerExtensionUnloadCallback(function() {
    cep.fs.writeFile("C:/Users/me/Desktop/appChache.txt", "app closed");
});
```

Thank you

**Comment by justintaylor-dev** [comment]
Some Adobe apps don't fire the onClose event, so I believe that's what the issue is. If you have CEP function that works in a vanilla project but not in Bolt, let me know.
