### ISSUE TITLE
Custom environment variables

### ISSUE THREAD

**Issue by vonstring** [hyperbrew/bolt-cep#41]
Sorry if this is more of a support request than an issue report, but:
I cannot figure out how to get custom environment variables into a Bolt extension.
I've tried with VITE_* variables in .env and import.meta.VITE_* according to [Vite's docs](https://vitejs.dev/guide/env-and-mode.html), and with the [React script approach](https://create-react-app.dev/docs/adding-custom-environment-variables/)(which I didn't really expect to work). Should either of these work? And if not, what's the best way to get variables into a Bolt extension at build time?

**Comment by justintaylor-dev** [comment]
Create a `.env` file and place it inside the `src/js` folder, make sure your vars start with `VITE_` as outlined here (https://vitejs.dev/guide/env-and-mode.html#env-files) and you'll want to make sure that's added to your `.gitignore`.  But note that these env vars are basically copied and pasted into your resulting code, so you'll probably want to encrypt them instead if they are sensitive.

Also, if you're trying to access system environment variables, use `process.env.VAR`.
