### ISSUE TITLE
not working after sometime

### ISSUE THREAD

**Issue by AnilSonix** [hyperbrew/bolt-cep#46]
![image](https://user-images.githubusercontent.com/14151192/208669302-af5a96be-464e-479d-b236-aed9bfd9cd84.png)
After I installed chakra-ui , the npm run build cmd showed above error.
It's a simple hello world code.
It worked for sometime initially, but after sometime HMR stopped.
And when I stopped the npm run dev, and tried to run npm run build , it showed above error.

**Comment by justintaylor-dev** [comment]
I've used Chakra UI on several React CEP projects just fine. You probably just need to update packages. If you're still having issues, post your `package.json`

**Comment by justintaylor-dev** [comment]
Looks like issue was due to skipLibCheck being set to `flase` in the tsconfig. You can set to true in your tsconfig or clone a new bolt-cep from version 0.5.2.

Same issue as: https://github.com/hyperbrew/bolt-cep/issues/45
