### ISSUE TITLE
`yarn zxp` -> Permission denied

### ISSUE THREAD

**Issue by JoshuaLelon** [hyperbrew/bolt-cep#50]
Hi, I'm on an M1 Mac.

I just created a new example project, following the below steps:

`yarn create bolt-cep myApp --template react`
`yarn`
`yarn build`

and then when I ran `yarn zxp`, I got

![CleanShot 2023-02-05 at 11 55 18](https://user-images.githubusercontent.com/23615754/216836530-4575dbe8-b8df-4ee6-8e22-8e2431ca7a64.png)

I also tried `sudo yarn zxp` and got the same error.

**Comment by justintaylor-dev** [comment]
Check out the steps in 

https://github.com/hyperbrew/bolt-cep#misc-troubleshooting

Essentially reset permissions for the ZXPSignCmd inside `/node_modules/vite-cep-plugin/bin`
