### ISSUE TITLE
/main/ loads a blank page after `yarn serve`

### ISSUE THREAD

**Issue by JoshuaLelon** [hyperbrew/bolt-cep#52]
I just created a new example project, following the below steps:

`yarn create bolt-cep myApp --template react`
`yarn`
`yarn build`
`yarn serve`

First I tried to go to `http:/localhost:5000/main/` and got a Permission denied error.

This was remedied when I changed `cep.config.ts:10` from `servePort: 5000` to `servePort: 3000` (apparently it conflicts with AirPlay? I'm on an M1 MacBook).

But then, when I went to

`http:/localhost:3000/main/`, I got a blank page:

![CleanShot 2023-02-05 at 12 10 03](https://user-images.githubusercontent.com/23615754/216837139-5d72625b-7a86-4ad6-84c2-cf3da68463e2.png)

It's not obvious to me if this is the intended result, but I would expect it to look like `http:/localhost:3000/main/` after I run `yarn dev`, i.e.

![CleanShot 2023-02-05 at 12 11 08](https://user-images.githubusercontent.com/23615754/216837167-e7f58417-e52b-405e-bff2-7c9245fa3b70.png)

**Comment by justintaylor-dev** [comment]
Port 3000 dev and 5000 serve are the defaults for Vite so I'm keeping them the same for now. The forward slash without any index.html is required in order to meet CEP specific requirements.

If I get more complaints of this, I can look into changing the defaults, but for now you can just change the port numbers in the config to something else. Thanks!

**Comment by JoshuaLelon** [comment]
to be clear, the port change isn't the issue - the issue (if it is an issue) is that going to `/main/` after `yarn serve` yields a blank page

**Comment by justintaylor-dev** [comment]
Closing for now. @JoshuaLelon If you still experience this issue after changing the port and or creating a fresh Bolt install, feel free to re-open this issue.
