### ISSUE TITLE
Not work in AE and PR 22

### ISSUE THREAD

**Issue by Yuelioi** [hyperbrew/bolt-cep#56]
It works well in AE2020 PR2020, 

but in PR/AE  21 & 22, I click "window -> bolt cep", nothing happen, 

(use vue template)

I try to change the CSXS version, not work either

**Comment by justintaylor-dev** [comment]
Make sure you have playerDebugMode turned on for all CEP versions.

You can do this with the command line or easily with the aescripts ZXPInstaller.

https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md

https://aescripts.com/learn/zxp-installer/

**Comment by Yuelioi** [comment]
> 

woooh, you are right , It works well now
