### ISSUE TITLE
Reload CEP panel extension and its ExtendScript without restarting?

### ISSUE THREAD

**Issue by Yuelioi** [hyperbrew/bolt-cep#57]
Thank you so much, this project is so useful

Today, when I was developing the pr extension, I found that I saved the local  file without restarting pr, and the extension was actually restarted, and I modified the jsx file, which also took effect

Before that, I was building now, and then put it in the pr extension folder,

But when I restart vscode, it suddenly fails. What is the normal debugging and expansion process? How can I reload CEP panel extension and its ExtendScript without restarting?

**Comment by justintaylor-dev** [comment]
You don't need to copy to the extension folder, a Symlink is auto-generated on `yarn build` for you to the right folder for your extension to work.

And you don't need to restart Premiere (any app) after saving changes if you're running `yarn dev` changes to the JS or ExtendScript side will hot-reload for you.

**Comment by justintaylor-dev** [comment]
closing for now.

If you're interested in chatting on getting started with Bolt CEP, feel free to join our Discord: https://discord.gg/BjPYRKUq
