### ISSUE TITLE
Ubuntu error

### ISSUE THREAD

**Issue by melih1996** [hyperbrew/bolt-cep#61]
Hi,
I've tried to install it but I got an error that says jsxbin@2.2.0: The platform "linux" is incompatible with this module.
How can I run the application inside Ubuntu 22?

**Comment by justintaylor-dev** [comment]
Adobe apps aren't compatible with Linux so we haven't tested compatibility for Bolt CEP.

JSXBIN certainly won't work since Adobe only provides.
