### ISSUE TITLE
Is there a way to display the screen share permission popup on the extension?

### ISSUE THREAD

**Issue by itsnitinr** [hyperbrew/bolt-cep#66]
I'm trying to build an extension that has the capability to screen share. While the popup for selecting the screen to be shared appears when I'm in development mode and on the browser, it doesn't show up after building the extension and opening it on Premiere Pro. Does Premiere Pro not allow such popups and is there a way to make this work? 

On browser:
![image](https://user-images.githubusercontent.com/34748469/232737670-56755ebc-bc73-4267-a7d4-6d2f56727285.png)

On extension:
![image](https://user-images.githubusercontent.com/34748469/232737926-68d03087-879d-471c-97df-dc68ef5eacb4.png)

**Comment by justadaniel** [comment]
Could it be a limitation of the bundled chromium engine? I know just from my own time with the implementation is that it's quite a "slimmed down" version of chromium with certain features to be disabled or removed.

**Comment by justintaylor-dev** [comment]
Yea like @justadaniel said, if it's a limitation, it has to do with CEP / Chromium limits not Bolt CEP. Maybe check here:

[https://github.com/Adobe-CEP/CEP-Resources](https://github.com/Adobe-CEP/CEP-Resources)

Could also try looking to see if there is an NW.js flag to enable this
