### ISSUE TITLE
`draggable="true"` doesn't seem to work

### ISSUE THREAD

**Issue by Yiddishe-Kop** [hyperbrew/bolt-cep#68]
adding `draggable="true"` to an HTML element inside a CEP panel doesn't seem to have any effect.

Anyone here knows how this works?

[Adobe CEP docs](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#drag-and-drop) states that it is supported. 

Thanks!

**Comment by justintaylor-dev** [comment]
This shouldn't have anything to do with Bolt CEP, likely a behavior in your framework of choice (e.g. vue, react, svelte). If you have something that works in a vanilla CEP project but not in a Bolt CEP project, feel free to re-open this issue.

**Comment by Yiddishe-Kop** [comment]
This seems to be a general CEP issue, as even native HTML draggable doesn't seem to work.

I thought people here might be able to help, but you're right, nothing to do with Bolt.

**Comment by justintaylor-dev** [comment]
@Yiddishe-Kop this is really just for Bolt-CEP issues, but you can join our Discord and ask the community:

[https://discord.gg/BnwHbakb](https://discord.gg/BnwHbakb)
