### ISSUE TITLE
Is it possible to configure the CEFCommandLine parameters?

### ISSUE THREAD

**Issue by jameslockman** [hyperbrew/bolt-cep#72]
The template injects the following parameters:
```
<CEFCommandLine>
  <Parameter>--v=0</Parameter>
  <Parameter>--enable-nodejs</Parameter>
  <Parameter>--mixed-context</Parameter>
</CEFCommandLine>
```

These parameters are customizable per [CEP Cookbook](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md). We would like to remove `--v=0` and add `--enable-file-cookies` as well as other parameters.

**Comment by justintaylor-dev** [comment]
@jameslockman you can change these in the `parameters` setting in `cep.config.ts`, although `--enable-file-cookies` was not in the type defs so I added that one in 1.1.3
