### ISSUE TITLE
ZXP bundling does not include .jsx files

### ISSUE THREAD

**Issue by Trentonom0r3** [hyperbrew/bolt-cep#73]
When I run 'yarn build' the project is built successfully, and everything functions as expected. 
However, when I run 'yarn zxp' and install that file, the extension does not work. 
After some digging, I figured out that the zxp bundle did not include the same jsx folder and index.js file that the build, and manual install for the extension does.  
My current workaround is dragging the jsx folder into the installed zxp, which works for now.
I'm not sure exactly where to begin on fixing this and haven't seen any similar issues in the repo. 

Thank you!

**Comment by GreenHapi** [comment]
I had the same problem. @justintaylor-dev just fixed it by updating the `vite-cep-plugin`. 
Please run `yarn add vite-cep-plugin` to update the plugin. And then rerun `yarn zxp`

**Comment by Trentonom0r3** [comment]
> I had the same problem. @justintaylor-dev just fixed it by updating the `vite-cep-plugin`. 
> 
> Please run `yarn add vite-cep-plugin` to update the plugin. And then rerun `yarn zxp`

Thank you so much!
