### ISSUE TITLE
ExtendScript gets highlighted as errors in aeft.ts

### ISSUE THREAD

**Issue by ikrupnov** [hyperbrew/bolt-cep#77]
<img width="385" alt="image" src="https://github.com/hyperbrew/bolt-cep/assets/118749970/134a777f-7d4c-4e7b-be0f-0d2f92028662">

Many elements get highlighted as errors but still the code works perfectly in AE. This is really frustrating. Maybe I do it wrong and I should write ExtendScript in a different file or in a different way?
The "errors" are like: 

> 'comp' is possibly 'null'. ts(18047)

> Property 'width' does not exist on type '_ItemClasses'. Property 'width' does not exist on type 'FolderItem'. ts(2339)

> Property 'layers' does not exist on type '_ItemClasses'. Property 'layers' does not exist on type 'FootageItem'. ts(2339)

**Comment by justintaylor-dev** [comment]
Those are all valid TS errors. Look up some learning resources on TypeScript to understand how to start writing code that solves these.
