### ISSUE TITLE
Typo in types-for-adobe/AfterEffects/../index.d.ts

### ISSUE THREAD

**Issue by ikrupnov** [hyperbrew/bolt-cep#79]
There is a method for the Project object: [app.project.itemByID(id)](https://ae-scripting.docsforadobe.dev/general/project.html#project-itembyid). So the method is described in index.d.ts but with typo:
<img width="452" alt="image" src="https://github.com/hyperbrew/bolt-cep/assets/118749970/cfe9e686-d013-4bd3-a03d-b9a1a04c78a7">
It should be ID, not Id.

**Comment by ikrupnov** [comment]
And there's also no method [layerByID](https://ae-scripting.docsforadobe.dev/general/project.html#project-layerbyid).

**Comment by ikrupnov** [comment]
And there's also no method [layerByID](https://ae-scripting.docsforadobe.dev/general/project.html#project-layerbyid).

**Comment by justintaylor-dev** [comment]
Create an issue or PR in [types-for-adobe](https://github.com/aenhancers/types-for-adobe)
