### ISSUE TITLE
Static Assets Handling

### ISSUE THREAD

**Issue by realningzheng** [hyperbrew/bolt-cep#97]
Hi!

Thanks for the great work! I'm wondering if there is a way to support static asset handling? e.g. import a static image from a "public" directory using the relative path, just like how it usually does in a normal react app or vite?

Thanks a lot!

**Comment by justintaylor-dev** [comment]
Static asset importing via Vite works out of the box, here's an example:

https://github.com/hyperbrew/bolt-cep/blob/44c8d5869b2d03de437bb492ba76123816ccf410/src/js/main/main.tsx#L12

If you need to just copy assets to the destination folder, then check out the copyAssets config in the array, but this is less common.

For usage questions like this, feel free to join our Discord: https://discord.gg/PC3EvvuRbc
