### ISSUE TITLE
Compiling zxp failed

### ISSUE THREAD

**Issue by nangonghan** [hyperbrew/bolt-cep#98]
On an Apple computer with an inter chip ,Compiling zxp failed,There are two reasons . 

The first zxpsigncmd has no executable permissions 
There is a problem with the relative path when the second execsync is executed, and it will be fine if it is replaced with exec 

<img width="1943" alt="image" src="https://github.com/hyperbrew/bolt-cep/assets/49426457/e8f32778-2820-4386-b4e2-a66e10f0549a">

The red line is the changed code and now it works

**Comment by nangonghan** [comment]
These codes are inside zxp.js

**Comment by nangonghan** [comment]
I can make do with this modification at present, but I still hope to optimize the problem from the source

**Comment by justintaylor-dev** [comment]
See the Misc Troubleshooting in the readme section for working on this:

https://github.com/hyperbrew/bolt-cep#misc-troubleshooting
