### ISSUE TITLE
Support pkg and exe export 

### ISSUE THREAD

**Issue by nangonghan** [hyperbrew/bolt-cep#99]

**Comment by justintaylor-dev** [comment]
Sounds like this is beyond the scope of Bolt CEP. If you have additional reasoning or examples please explain.

**Comment by nangonghan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by justintaylor-dev** [comment]
I'm closing this issue. We recommend installing and recommend your customers install extensions with ZXP Installer from aescripts:

https://aescripts.com/learn/zxp-installer/

You can add your own installers as a separate step that happens after running `yarn zxp` but you'll need to build per platform.
